### ISSUE TITLE
with mark.innerHTML isn't possible copy iframe string

### ISSUE THREAD

**Issue by Pave91** [sudodoki/copy-to-clipboard#10]
With mark.textContent  it worked fine.
I have for example this string <iframe src="http://google.com" width="960" height="1300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" style="overflow: hidden;"> and it won't copy at all, no error is displayed.

**Comment by sudodoki** [comment]
Thanks for heads up. Can you provide sample fiddle/jsbin to reproduce this? Meanwhile suggest  locking dep on previous version.

**Comment by Pave91** [comment]
I'm sorry, I wanted post this string into comment, just try put as text this:
`<iframe src="http://edu.trunk.postra.gsvn//glog/32590" width="960" height="1300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" style="overflow: hidden;"></iframe>`

**Comment by sudodoki** [comment]
@shvaikalesh do you have any advice on resolving this issue?

**Comment by shvaikalesh** [comment]
`.innerHTML` assignment ~~sucks~~ causes this issues.
However, it has good reasoning for being there (see #7).
One way of handling this issue is to escape HTML manually ([like here](https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/utils.js))

Other way of handling this is bring `.textContent` back and play with `white-space` on created `<mark>` element.

**Comment by Pave91** [comment]
@sudodoki is it possible to include escaping like @shvaikalesh suggest?

**Comment by sudodoki** [comment]
@Pave91 got no idea atm, will try to tackle this when I have free time on my hands.

**Comment by sudodoki** [comment]
Sorry.

**Comment by Pave91** [comment]
It's fine, I think I can send escaped string myself. Thanks to @shvaikalesh for showing the way.

**Comment by sudodoki** [comment]
Should be fixed by #19 let me know, if latest master works for you and I'll publish version. @Pave91

**Comment by Pave91** [comment]
Works fine for me, thanks. You can publish it.

**Comment by sudodoki** [comment]
Closing this then
