### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by qb-rivkyb** [sudodoki/copy-to-clipboard#114]
Hi,
I was wondering if this package is deprecated since the execCommand is deprecated like it says in the MDN docs. https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand. I am having issues that it is pasting undefined.

**Comment by vedraan** [comment]
While officially deprecated it will take some (long?) time before browsers start to drop support. Right now it's still very much supported, see:
https://caniuse.com/document-execcommand
