### ISSUE TITLE
npm audit: 16 vulnerabilities

### ISSUE THREAD

**Issue by matsamuel2018** [sudodoki/copy-to-clipboard#116]
The latest version of copy-to-clipboard contains some vulnerabilities according to "npm audit":
16 vulnerabilities (1 low, 4 moderate, 6 high, 5 critical)

I'm not using this package directly but instead it is being referenced through antd (and I'm using antd). But I'm just seeing if this project is active enough that perhaps these vulnerabilities will be addressed at some point. I'm certainly no expert with this but it appears that the vulnerabilities are related to packages that need upgrading to newer versions.

**Comment by sudodoki** [comment]
Yep, sure, buddy, eventually we will do everything, but meanwhile

> # 🇺🇦 UKRAINE NEEDS YOUR HELP NOW!
>
> I'm the creator of this project and I'm Ukrainian.
>
> **My country, Ukraine, [is being invaded by the Russian Federation, right now](https://www.bbc.com/news/world-europe-60504334)**. I've fled Kyiv and now I'm safe with my family in the western part of Ukraine. At least for now.
> Russia is hitting target all over my country by ballistic missiles.
>
> **Please, save me and help to save my country!**
>
> Ukrainian National Bank opened [an account to Raise Funds for Ukraine’s Armed Forces](https://bank.gov.ua/en/news/all/natsionalniy-bank-vidkriv-spetsrahunok-dlya-zboru-koshtiv-na-potrebi-armiyi):
>
> ```
> SWIFT Code NBU: NBUA UA UX
> JP MORGAN CHASE BANK, New York
> SWIFT Code: CHASUS33
> Account: 400807238
> 383 Madison Avenue, New York, NY 10179, USA
> IBAN: UA843000010000000047330992708
> ```
>
> You can also donate to [charity supporting Ukrainian army](https://savelife.in.ua/en/donate/).
>
> **THANK YOU!**

**Comment by sudodoki** [comment]
@matsamuel2018 let me know whether 3.3.2 gives you the same issue
