### ISSUE TITLE
Screen readers should not narrate copied text

### ISSUE THREAD

**Issue by amccarthy1** [sudodoki/copy-to-clipboard#119]
Hi there! I'm testing my application with a screen reader (I'm using ChromeVox, but I could see this occurring with other tools) and I noticed that when I use `copy`, it narrates the text that was copied. This is likely highly dependent on browser / technology combination.

In my application, I have a "Copy ID" button (it's a developer tool), and clicking the button narrates out a very long ID, which is pretty disruptive. Ideally, nothing would narrate on copy, and an app can provide textual feedback that the copy went through.

The root is that when creating a span to artificially select, the library does not set the `aria-hidden` attribute on that span to `true`.

I would imagine most people don't intend for the copied text to be narrated, so it's probably pretty safe to make this change by default. Happy to contribute a PR to fix this!

**Comment by sudodoki** [comment]
Great point. I see, I'll get back to you for retesting, if you don't mind.

**Comment by sudodoki** [comment]
@amccarthy1 can you please test it on 3.3.2?

**Comment by amccarthy1** [comment]
It works correctly now. Thank you so much for the quick turnaround!
