### ISSUE TITLE
not working for script tags

### ISSUE THREAD

**Issue by IonutLaceanu** [sudodoki/copy-to-clipboard#14]
I want a copy button for a text which basically is a script tag.
Something like:

```
<script type="text/javascript">
  var a = 2 + 3;
</script>
```
However, it doesn't work, becuase you are using innerHTML, which basically inserts the script inside the page.

**Comment by nkbt** [comment]
Is it fixed if innerHTML is changed to innerText? Most likely it should be working...

**Comment by nkbt** [comment]
http://codepen.io/nkbt/pen/eJrdWG?editors=0010

@IonutLaceanu, that works just well for me with your example. Maybe you are doing something else oddly?

**Comment by IonutLaceanu** [comment]
@nkbt, it works because you are copying the content of the script tag.
In my case, I want to copy the entire script tag.
in your code pen, enter this:
```<script type="text/javascript" ref="script">var a = 2 + 3;</script>```
in the input field, 
then, make sure that you have something else in your clipboard (copy some random stuff)
then do copy to clipboard from button.

You'll see that it doesn't work.

I'll try with inner text and see if it works, but still, the problem is that you are appending the tag to the DOM. that's not really ok, because it gets evaluated. why aren't you using a textarea or something else?

**Comment by IonutLaceanu** [comment]
@nkbt, I can confirm that it works like a charm with ```innerText```

**Comment by nkbt** [comment]
Well, yeah, if you paste `script` as innerHTML that should not really work. Moreover that is quite dangerous =). I would not recommend doing that. But changing to `innerText` seems like a really good idea (for safety reasons too. Keen to PR?

**Comment by nkbt** [comment]
Might be related to https://github.com/nkbt/react-copy-to-clipboard/issues/15

**Comment by sudodoki** [comment]
@nkbt will try to find time this week

**Comment by nkbt** [comment]
Thanks, @sudodoki.

I think you can also try to create a `textarea` instead of `div`.

**Comment by sudodoki** [comment]
Should be fixed by #19 let me know, if latest master works for you and I'll publish version. @nkbt @IonutLaceanu.

**Comment by sudodoki** [comment]
Considering this closed now. Please, let me know if something still doesn't work for you.
