### ISSUE TITLE
Text will be stripped if it contains <>

### ISSUE THREAD

**Issue by magicae** [sudodoki/copy-to-clipboard#16]
```
<!>
```
It will be stripped in Chrome.

**Comment by sudodoki** [comment]
Might be related to https://github.com/sudodoki/copy-to-clipboard/issues/14

**Comment by sudodoki** [comment]
Should be fixed by #19. Let me know, if latest master works for you and I'll publish version. @magicae

**Comment by magicae** [comment]
Works fine, thanks!
