### ISSUE TITLE
Error messages in Chrome

### ISSUE THREAD

**Issue by shvaikalesh** [sudodoki/copy-to-clipboard#2]
If there is a `text selection` on a page and `copy` function is invoked (as a result of some user action), Chrome 43/45 prints `Discontiguous selection is not supported` in console and *does not* copy anything to the clipboard. And if it does, text selection is not restored (because of the lack of `Selection.removeRange` method).

Furthermore, `text selection` I have mentioned could be 0-length: any click on any text causes selection of `type: "Caret"`. So this kinda bug happens quite often.

What I am proposing is to remove and restore user selection after copying to clipboard. This will solve both mentioned issues (errors in console and not restored text selection).

What do you think, @sudodoki?

**Comment by sudodoki** [comment]
@shvaikalesh yep, had that idea as well when was testing the example page last time. Thanks for the `type: "Caret"` mention - didn't know about that.

**Comment by nkbt** [comment]
@sudodoki do you reckon any working solution available for this? I am not quite sure I want to go this way: https://github.com/nkbt/react-copy-to-clipboard/pull/6

**Comment by sudodoki** [comment]
@nkbt there's an easy fix by just removing all selection before calling the copy method. What I wanted to do was to deselect everything and return selection afterwards - working on this in private repo atm, but not too much progress on replication previously selectedRange that would work.

**Comment by sudodoki** [comment]
@nkbt I will try to get some more time and if nothing works - will go with easier path of just removing selection.

**Comment by shvaikalesh** [comment]
@sudodoki I have kinda did that long time ago in:
https://github.com/sudodoki/toggle-selection/commits/master
It works, check out commit history -- therea are couple of messages in comments there

**Comment by sudodoki** [comment]
@shvaikalesh :tired_face: oh my glob, so missed this out, sorry.

**Comment by sudodoki** [comment]
Should be fixed via https://github.com/sudodoki/copy-to-clipboard/pull/5

**Comment by nkbt** [comment]
\o/ awesome!
