### ISSUE TITLE
Callback if copy successful

### ISSUE THREAD

**Issue by philster** [sudodoki/copy-to-clipboard#20]
Just curious if there's a way to detect if copy is successful? If so can we expose a callback function option to let users perform custom actions on successful copy? Thanks!

**Comment by sudodoki** [comment]
Thought about this. It's sync action in chrome and ie, afaik, but will be
async in case of prompt. What's your usecase? Just curious
26 февр. 2016 г. 9:14 PM пользователь "Phil Wee" <notifications@github.com>
написал:

**Comment by philster** [comment]
Other than the prompt (for example in Safari), I need to notify the user via window.alert or some status text that the copy was successful. Similar to what's done in [react-copy-to-clipboard](https://github.com/nkbt/react-copy-to-clipboard), except that in react-copy-to-clipboard, it always says "Copied" even if sometimes the copy was not successful.

**Comment by sudodoki** [comment]
@philster would you care to add `callback` to options and send a PR?
