### ISSUE TITLE
Not working in FF Version 42

### ISSUE THREAD

**Issue by sunnybogawat** [sudodoki/copy-to-clipboard#21]
I am using this in my react component and found that for FF 36 and 42.0 it's not working. Do you know any workaround to solve this issue

**Comment by sudodoki** [comment]
@sunnybogawat can you provide a jsbin/plunkr/jsfiddle?

**Comment by sunnybogawat** [comment]
It is working with latest version of FF I am getting issue only with version 42.0 
On button event I am executing following code which would copy output from innerHTML 

`copy(this.refs.outputFormat.innerText);`

**Comment by sudodoki** [comment]
@sunnybogawat issue is with FF 42 is not supporting `innerText`. http://caniuse.com/#feat=innertext
Use `innerHTML` or `textContent` instead. Hope this helps
