### ISSUE TITLE
Stopped working on Chrome

### ISSUE THREAD

**Issue by kof** [sudodoki/copy-to-clipboard#28]
My chrome version on mac: Version 50.0.2661.102 (64-bit)

Not sure if something real weird happened to my chrome or chrome released something that broke it. It has been working all the time and works on all other browsers.

**Comment by sudodoki** [comment]
Which version of package are you running?
1 июня 2016 г. 7:40 PM пользователь "Oleg Slobodskoi" <
notifications@github.com> написал:

**Comment by kof** [comment]
Oh sorry, tried 3.0.0 and 3.0.1

**Comment by kof** [comment]
Can you reproduce that?

**Comment by sudodoki** [comment]
Looking into it…

**Comment by sudodoki** [comment]
@kof this is not happening on 3.0.0, this is specific to https://github.com/sudodoki/copy-to-clipboard/blob/master/index.js#L25-L28 lines. Can you temporarily switch back to 3.0.0 while I'll investigate this further?

**Comment by kof** [comment]
Sure, probably I was using 3.0.1 recently and thought it is 3.0.0

**Comment by sudodoki** [comment]
Can you try using latest master – it worked for me, but I'm going to wait before publishing it right away?

**Comment by kof** [comment]
As you could reproduce the issue in chrome and this clearly fixes it, I think you can publish a patch, because current version is broken anyways and all users who has ^ in the version are getting it. So it can be only better and you will get more feedbacks.

**Comment by sudodoki** [comment]
Hm, might make sense. It's out: [3.0.2](https://github.com/sudodoki/copy-to-clipboard/releases/tag/v3.0.2)

**Comment by kof** [comment]
3.0.2 works for me
