### ISSUE TITLE
OS detection

### ISSUE THREAD

**Issue by shvaikalesh** [sudodoki/copy-to-clipboard#3]
`window.prompt('Copy to clipboard: Ctrl+C, Enter', text);`

It is Cmd+C on Mac, and it would be great if copy-button did some UA/OS sniffing to show appropriate messages.

Also, messages like "double tap and choose copy" can be displayed on handheld devices.

Furthermore, it is possible to detect whether virtual keyboard or hardware one is used (innerHeight property of window shrinks when most of mobile keyboards slide up, except for iOS).

Just couple of ideas of mine.

**Comment by sudodoki** [comment]
<3 for ctrl/cmd stuff
Regarding virtual keyboard - had 'awesome' experience with this technic, quite sceptical about it, but we can try

**Comment by sudodoki** [comment]
Possibly, could use `navigator.platform` value and match it for 'Mac' inclusion

**Comment by shvaikalesh** [comment]
`navigator.platform` is deprecated, but it will tell exactly that user is on Mac or on iOS.

However, iOS devices consider command/windows a meta key, so `/mac os x/i.test(navigator.userAgent)` will be ok.
