### ISSUE TITLE
Breaks universal rendering

### ISSUE THREAD

**Issue by nkbt** [sudodoki/copy-to-clipboard#39]
https://github.com/sudodoki/copy-to-clipboard/commit/a3e3d1547d5f5d65659cc621cdcdcaf5c3720510#diff-168726dbe96b3ce427e7fedce31bb0bc change breaks universal rendering since `navigator` is undefined on the server.
Usually it worked fine since we were copying after some user interactions and `copy-to-clipboard` was never run on the server.

**Comment by nkbt** [comment]
Also breaks unit tests, so I had to temporarily do this workaround: https://github.com/nkbt/react-copy-to-clipboard/commit/868e329518a91c251aeb3987514af1c13d35f849#diff-910eb6f57886ca16c136101fb1699231R14

**Comment by shvaikalesh** [comment]
Why can not server supply `userAgent` from HTTP request?

**Comment by goldensunliu** [comment]
@shvaikalesh that is the general idea. the lib needs an interface for the user to provide the userAgent as a dependency. a common pattern is like this one here http://www.material-ui.com/#/get-started/server-rendering

**Comment by nkbt** [comment]
I think it is unnecessary to provide copy-to-clipboard with useragent, it affects message that can appear after user interaction **only**, which would be never used on server-side rendering. So just moving user-agent check inside the function (actually to the place where it is needed - **catch**, so it most likely would never be used) should be sufficient

**Comment by nkbt** [comment]
^ PR https://github.com/sudodoki/copy-to-clipboard/pull/40

**Comment by nayanbhana** [comment]
+1
