### ISSUE TITLE
 Copied text has yellow background when pasted into gmail or google docs

### ISSUE THREAD

**Issue by nkbt** [sudodoki/copy-to-clipboard#43]
Can reproduce from here

http://codepen.io/nkbt/pen/eNPoQv?editors=0010

Weird stuff

![copy-to-clipboard-yello-back](https://cloud.githubusercontent.com/assets/175264/17639923/0bf01f60-613b-11e6-9f45-00fc2ddbfbcf.gif)

**Comment by shvaikalesh** [comment]
Nice, that because of UA stylesheet for [`<mark>`](https://github.com/sudodoki/copy-to-clipboard/blob/master/index.js#L22) element. I've used it because it matches semantically, who cares, will change back to `<span>`.

**Comment by nkbt** [comment]
thanks @shvaikalesh when was it changed?

**Comment by shvaikalesh** [comment]
Like a year ago or something.

**Comment by shvaikalesh** [comment]
Even with `<span>` there are concerns with styles (like `span { background: red }`)...

**Comment by nkbt** [comment]
wow, nobody noticed =)

**Comment by sudodoki** [comment]
Published in 3.0.5

**Comment by sudodoki** [comment]
Thanks for bug report!
