### ISSUE TITLE
Typescript definition?

### ISSUE THREAD

**Issue by DenisCarriere** [sudodoki/copy-to-clipboard#49]
I was going to publish a TypeScript definition for this module.

@sudodoki Any interest to include this directly in your library or would you rather have it maintained and published under [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

The definition is pretty straightforward and won't be very complicated (<10 LOC)

**Comment by sudodoki** [comment]
Yeah, I would gladly accept PR with it, thanks in advance!

**Comment by DenisCarriere** [comment]
👍 ok perfect, that was a faster response than expected, I'll close my PR to DT.

**Comment by DenisCarriere** [comment]
Sent via PR https://github.com/sudodoki/copy-to-clipboard/pull/50
