### ISSUE TITLE
Not working in the Firefox@54.0.1

### ISSUE THREAD

**Issue by nkbt** [sudodoki/copy-to-clipboard#53]
Reposted https://github.com/nkbt/react-copy-to-clipboard/issues/70

> Hi, I use FF Version 54.0.1 where copy does not work for me (no error; just nothing happens). In chrome it works perfectly. Is there an issue when using firefox in general or should it work? Thanks for a short feedback!

**Comment by sudodoki** [comment]
Works for me (can try it on http://sudodoki.github.io/copy-to-clipboard/example/)
macOS 10.12.5, FF 54.0.1 (64-bit).

**Comment by sudodoki** [comment]
maybe, some extension to blame?

**Comment by sudodoki** [comment]
let me know if you get more debug info
