### ISSUE TITLE
Add a flow type definition to the flow-typed project

### ISSUE THREAD

**Issue by NameFILIP** [sudodoki/copy-to-clipboard#54]
Should be easy to convert from the TypeScript definition.

[flow-typed repo](https://github.com/flowtype/flow-typed)
[Contributing Library Definitions](https://github.com/flowtype/flow-typed/wiki/Contributing-Library-Definitions)

**Comment by sudodoki** [comment]
PR is welcome, won't do it myself

**Comment by NameFILIP** [comment]
https://github.com/flowtype/flow-typed/pull/1126

**Comment by sudodoki** [comment]
https://github.com/flowtype/flow-typed/commit/8ece034ea17989e2db009e8831e549932328beac
