### ISSUE TITLE
copy failed and popup a dialog on iphone

### ISSUE THREAD

**Issue by ChandaZhou** [sudodoki/copy-to-clipboard#59]
![copy-issue-ios9](https://user-images.githubusercontent.com/17309468/32646860-a0c6dcf6-c629-11e7-86ff-92e287a77eb1.png)

**Comment by sudodoki** [comment]
@ChandaZhou hi! Can you provide version of ios used?

**Comment by qqqhuohuo7** [comment]
i hava the same problem... chrome v62
just alert text

**Comment by sudodoki** [comment]
@qqqhuohuo7 can you provide repro case or let me know, if http://sudodoki.github.io/copy-to-clipboard/example/ doesn't work for you?

**Comment by sudodoki** [comment]
@qqqhuohuo7 sorry, given you didn't provide anything, I would write this off as 'closed' for time being. Feel free to dump things here when you find them and I'll reopen.

**Comment by fiftin** [comment]
@sudodoki I have similar problem on iPhone.

I have this message, if I try to copy result of AJAX request.

**Comment by shvaikalesh** [comment]
@fiftin Please see https://github.com/sudodoki/copy-to-clipboard/issues/65#issuecomment-436607745
