### ISSUE TITLE
Define "older IOS versions"

### ISSUE THREAD

**Issue by MACscr** [sudodoki/copy-to-clipboard#61]
Can you please define what is considered an "olde ios version" that this script wont work with? I mean, anything but the latest patch would be considered older and I dont think thats the case. What version and under does it actually not work on of iOS? 8?

**Comment by sudodoki** [comment]
good question. Supposedly, iOS 7 and up should work. For sure, I did test on iOS 10 only and cannot remember whether I tested iOS 9, but there's a possibility. Current version of iOS is 11.2.

**Comment by MACscr** [comment]
That's great news. Seems like it should work with most devices from the past 4 years or so and maybe even longer if they updated their software.

**Comment by sudodoki** [comment]
So, I suppose this can be closed now 😅
