### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by ButuzGOL** [sudodoki/copy-to-clipboard#64]
(node:57623) UnhandledPromiseRejectionWarning: TypeError: reselectPrevious is not a function
    at copy (/Users/butuzgol/Desktop/game/game/node_modules/copy-to-clipboard/index.js:72:5)
    at start$ (/Users/butuzgol/Desktop/game/game/data/helpers.js:38:3)
    at tryCatch (/Users/butuzgol/Desktop/game/game/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)

**Comment by ButuzGOL** [comment]
➜  game git:(master) ✗ node -v
v8.11.1
➜  game git:(master) ✗ npm -v
5.8.0
➜  game git:(master) ✗ yarn -v
1.5.1
➜  game git:(master) ✗

**Comment by ButuzGOL** [comment]
"babel-cli": "^6.26.0",

**Comment by sudodoki** [comment]
I still don’t have enough info, seems that you are using this not in browser, which won’t work as it relies on some DOM apis. Maybe https://www.npmjs.com/package/node-clip or some other package will work for you. Closing this for now. In case you are actually getting this error when doing SSR or running app in browser, let me know the details about browser/code that emits this error

**Comment by ButuzGOL** [comment]
sorry thought its also node support
