### ISSUE TITLE
how to copy text from ajax result

### ISSUE THREAD

**Issue by yourVictor** [sudodoki/copy-to-clipboard#65]
how to copy text from ajax result?

**Comment by chrisrobbins85kw** [comment]
@yourVictor when you try to do this what errors are being thrown?

**Comment by yourVictor** [comment]
show a pop box which contain an input with the text which want to copy

**Comment by yourVictor** [comment]
@chrisrobbins85kw  show a pop box which contain an input with the text which want to copy

**Comment by yourVictor** [comment]
![image](https://user-images.githubusercontent.com/20289879/42548795-7e3e43a4-84fb-11e8-9da2-d99c60c31f50.png)

**Comment by tymochko** [comment]
Today I noticed the same issue. Is there a work around yet with this?

**Comment by sudodoki** [comment]
there might be security restriction in play here that you cannot just copy text unless there is user interaction. One workaround might be after getting ajax response add a button 'copy response' or whatever and try doing copy then (given you already now what you want to copy).

**Comment by tymochko** [comment]
@sudodoki , thanks for reply.
As I see now this "copy" functionality only works for events when user interacts with site:
https://www.w3.org/TR/clipboard-apis/#integration-with-other-scripts-and-events

**Comment by sudodoki** [comment]
considering this non-issue then
