### ISSUE TITLE
Bump toggle-selection

### ISSUE THREAD

**Issue by lhache** [sudodoki/copy-to-clipboard#67]
Following this issue https://github.com/nkbt/react-copy-to-clipboard/issues/20

**Comment by sudodoki** [comment]
are you still having issues described in original thread because of getting older dependency?

**Comment by sudodoki** [comment]
there might be other issues now with this package being somewhat old and browser api possibly changing

**Comment by lhache** [comment]
I still do indeed. Bumping to the newer version does help.
