### ISSUE TITLE
Android webview not work?

### ISSUE THREAD

**Issue by Bouqute** [sudodoki/copy-to-clipboard#70]
Projects made with reactjs are opened in Android webview, copying cannot be used

**Comment by sudodoki** [comment]
@Bouqute do you know which webview/chromium version is used? Can you link to repro case?
Supposedly, execCommand doesn't work 
![image](https://user-images.githubusercontent.com/1506905/47613803-04803880-da9e-11e8-8ab0-1a74be6f3f60.png) and I wonder whether prompt is working there.

**Comment by sudodoki** [comment]
Maybe you'll need some custom code for webview version specifically.

**Comment by kwzm** [comment]
@sudodoki Hi, can you tell me where this red picture comes from, thanks.

**Comment by sudodoki** [comment]
@kwzm probably it was caniuse https://caniuse.com/#feat=document-execcommand

**Comment by kwzm** [comment]
@sudodoki Thanks, I guessed it was but not sure :smile:
