### ISSUE TITLE
Error using clipboard-copy on glitch.com

### ISSUE THREAD

**Issue by Rotimi-Best** [sudodoki/copy-to-clipboard#71]
I am hosting my app on glitch.com and running the code below give an error message

**Code:**
```javascript
const copy = require('clipboard-copy');

copy('copied');
```

**Error Message:** 
_UnhandledPromiseRejectionWarning: ReferenceError: navigator is not defined at clipboardCopy (/rbd/pnpm-volume/9f6c9fba-aa0c-4aca-a74c-4ee444e59487/node_modules/.registry.npmjs.org/clipboard-copy/2.0.1/node_modules/clipboard-copy/index.js:5:3)_

**Comment by sudodoki** [comment]
@Rotimi-Best where are you running this code? In glitch itself in scripts that ran in browser, `require` wouldn't be defined, and if it's defined, you probably run this on server, which won't work.
Let me know whether you have figured this out, right now don't think it's enough info to figure this out.

**Comment by Rotimi-Best** [comment]
I ran it  in on the server.

> you probably run this on server, which won't work

Yes this is right, why didn't it work since it ran on my local machine?
