### ISSUE TITLE
Anyway to disable the prompt? 

### ISSUE THREAD

**Issue by hanweifish** [sudodoki/copy-to-clipboard#72]
We can config but cannot disable it. Thanks.

**Comment by yshterev** [comment]
@jansesun You can disable it by passing wrong type to `message` like `null`. 

Prompt won't show, but you get a js error instead :)

**Comment by sudodoki** [comment]
@yshterev sure, go ahead

**Comment by sudodoki** [comment]
I think @hanweifish it might be useful to either
1) have window.prompt stubbed to do nothing
2) drop in index.js & remove window.prompt calls in your version.

Closing this for now, let me know if this is a major issue and you strongly believe this should be done in lib itself.

**Comment by suiyi8760** [comment]
@yshterev It dosen't seem to work right now

**Comment by darmawan01** [comment]
is there any solution for this ?
