### ISSUE TITLE
Broken wzrd.in link to library

### ISSUE THREAD

**Issue by potapenko** [sudodoki/copy-to-clipboard#73]
https://wzrd.in/standalone/copy-to-clipboard@latest

**Comment by sudodoki** [comment]
@potapenko seems that `wzrd.in` landing page works but not the backend part responsible for actual CDNing - getting 504 from cloudflare. If it isn't resolved until sunday, just gonna remove link from readme. Thanks for noticing!

**Comment by sudodoki** [comment]
seems fixed now

**Comment by qrqhuang** [comment]
`wzrd.in` stuck again. Not stable to user.
