### ISSUE TITLE
Please remove comments in source files

### ISSUE THREAD

**Issue by garygao12580** [sudodoki/copy-to-clipboard#74]
Please remove comments in source files. Or export a lib file without comments.

**Comment by sudodoki** [comment]
Can you please provide context of why you need this?

**Comment by garygao12580** [comment]
I used this package in my project, resulting in the packaged code containing comments, but our online project is not allowed to include comments. So, could you post an NPM package without comments?

**Comment by sudodoki** [comment]
What do you use for bundling code? What about postprocessing that would remove code comments? Right now there's no prebuilt lib, just index.js that is supposedly for end-user to mangle and minify any way they like.

**Comment by garygao12580** [comment]
Our project is special and only some files are compressed.
Or could you provide a beta version with the comment removed? This will solve our problem.
we use gulp to bundle and process.

**Comment by sudodoki** [comment]
You can use [copy-to-clipboard/example/index.js](https://github.com/sudodoki/copy-to-clipboard/blob/master/example/index.js) for this purpose

**Comment by garygao12580** [comment]
You resolved my problem. Thanks.
