### ISSUE TITLE
Consider replacing the use of `selectNode` by `selectAllChildren` or `selectNodeContents`

### ISSUE THREAD

**Issue by julienw** [sudodoki/copy-to-clipboard#75]
In the current version of the library, we select the text to be copied by using this code:
```js
range.selectNode(mark);
selection.addRange(range);
```
The problem with `selectNode` is that it selects the Node itself, which has comme unfortunate consequence that the Selection object gets `focusNode` and `anchorNode` set to `body` which is the parent of the element. This is expected [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/range/selectNode):

> The Range.selectNode() method sets the Range to contain the Node and its contents. The parent Node of the start and end of the Range will be the same as the parent of the referenceNode.

The direct consequence is that the `copy` event's target is then `body`, while it would be better if it was the range itself (more about that below).

An easy way to fix it is to replace `range.selectNode` by `range.selectNodeContents`. Another way is to replace using a `range` and directly use `selection.selectAllChildren`, but then we need to also change (maybe simplify?) the way we remove the selection by always calling `selection.removeAllRanges()`.

Now, why is that useful ?
Because I think the component should stop the propagation of the "copy" event by adding something like:
```js
    mark.addEventListener('copy', e => e.stopPropagation());
```
This is useful because applications commonly add a `copy` event handler on the `body` to handle ctrl-c operations (that's what we do in our app indeed!). It's on `body` because there are some cross-browser issues about what the `target` should be in some situations.

But in my opinion the `copy` event provoked by `copy-to-clipboard` is an unfortunate side effect of the method we use to copy, and so it should just be invisible to the outer code.

I'll be happy to do the patch if you think the changes are useful.

**Comment by julienw** [comment]
I did the patch in #76 and confirmed it fixes my problem.

**Comment by sudodoki** [comment]
It's in [3.1.0](https://github.com/sudodoki/copy-to-clipboard/releases/tag/v3.1.0)
