### ISSUE TITLE
How do I get the copied content from the clipboard

### ISSUE THREAD

**Issue by peachapp** [sudodoki/copy-to-clipboard#78]
When I put the content behind the clipboard.How do I get the copied content from the clipboard

**Comment by sudodoki** [comment]
@peachapp 
1) store it in variable somewhere
2) `e.clipboardData.getData` might be useful, where e is during 'paste' event handler
3) https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#Reading_from_the_clipboard

Hope this helps

**Comment by peachapp** [comment]
The problem has been solved, thank you
