### ISSUE TITLE
Fragments Break Copy Functionality

### ISSUE THREAD

**Issue by seth-wat** [sudodoki/copy-to-clipboard#86]
Giving `CopyToClipboard` a fragment as a child will break the copy functionality

```js
  return (
    <CopyToClipboard text={url} onCopy={toggle}>
      <>
        <Button key="clipboard" icon tooltipLabel={t('Copy Link')}>
          link
        </Button>
      </>
    </CopyToClipboard>
  )
```

**Comment by sudodoki** [comment]
Are you using https://github.com/nkbt/react-copy-to-clipboard ? Did you try getting help through their community? Also, when reporting similiar issues would be useful to provide error / stacktrace and even better - a reproducible code sandbox example.
Not sure this issue as is is workable, closing for now.
