### ISSUE TITLE
Prompt on cypress

### ISSUE THREAD

**Issue by cesarlima-hotmart** [sudodoki/copy-to-clipboard#88]
Prompt alert when testing the application with cypress. Is there a way to solve it?

**Comment by sudodoki** [comment]
I guess just disabling fallback might be an okay~ish thing for such case, if you don't need to test successful copying. Then either using fork right now from https://github.com/sudodoki/copy-to-clipboard/pull/82/files or waiting for it to be merged, which also needs some readme/typing updates

**Comment by cesarlima-hotmart** [comment]
In fact, i'm testing if the text is successfully copied to clipboard.

**Comment by sudodoki** [comment]
@cesarlima-hotmart then you might be in trouble :grimacing: see https://github.com/sudodoki/copy-to-clipboard/tree/master/tests and https://github.com/sudodoki/copy-to-clipboard/blob/master/e2e_helpers/assertions/assertBuffer.js for possible references. I used extra elements to do 'reseting' of the buffer by calling ctrl/cmd+c with some text selected and pasted stuff into textarea/etc to verify I was able to copy something from buffer and that stuff I needed was copied.
I wasn't able to reliably write tests for at least most commong platforms (Chrome / Firefox) as it seemed line endings were inconsistent across different browsers, so I ended up with regexes that were more relaxed with whitespacing than exact matches on strings

**Comment by cesarlima-hotmart** [comment]
Yeah, cypress runs on chromium, but i think the problem is the app runs in a webview inside it. The weird thing is, it works if I click manually on the button that calls the copy, but it prompts if i click on it by cypress.

**Comment by sudodoki** [comment]
there're some issues with security which might be in play, as execCommand cannot be executed without user's interaction, not sure whether that's the case here

**Comment by cesarlima-hotmart** [comment]
The solution i've found is check the parameters of the alert and assume that it is going to be the copied value in the real scenario.
```typescript
cy.window().then(win => {
  cy.stub(win, 'prompt').returns(win.prompt).as('copyToClipboardPrompt');
});

let link: string;

cy.get('.transmission-info-container .info .column:last-child .link').find('a').then($a => {
  link = $a.text().trim();
});

cy.get('.transmission-info-container .info .column:last-child .link > div').click();
cy.get('@copyToClipboardPrompt').should('be.called');
cy.get('@copyToClipboardPrompt').should(prompt => {
  expect(prompt.args[0][1]).to.equal(link);
});
```

**Comment by KateKorneeva** [comment]
Thank you!

**Comment by She-Wolf** [comment]
@cesarlima-hotmart 
I lost 2 days before find your solution. Good life and good health to you !

**Comment by inoutw** [comment]
@cesarlima-hotmart thanks, it works fine in cypress test runner, but when I run it as a node module ( by command **npx cypress run --spec "cypress/**/my-spec.js"**) it showed error as  `AssertionError: Timed out retrying after 15000ms: expected copyToClipboardPrompt to have been called at least once, but it was never called`

**Comment by pR13S7** [comment]
> ```ts
> .args[0][1]
> ```

God bless you man!

**Comment by tit** [comment]
@cesarlima-hotmart
This world bless you. Thanks!

**Comment by TophatRay** [comment]
@inoutw Did you ever find a solution to to your assertion error? I'm having similar issues

Update: Turns out what happens is that Electron does not support alerts, so the "prompt" action didn't register.
To get around this issue I just had a modal/message pop up that shows me what I copied and did a simple
```
.contains(`Copied ${copiedData}`).should("exist");
```
