### ISSUE TITLE
how can i know if it is success?

### ISSUE THREAD

**Issue by lijicheng123** [sudodoki/copy-to-clipboard#97]
is there any success callback and fail callback ?
or tell me success or fail?

**Comment by sudodoki** [comment]
@lijicheng123 I don't think there's much that can be done in that regards.
many things can go wrong:
- a generic exception (hopefully we fix this for different platforms, but there are some exotic cases)
- security measures taken by browser, that will mean copy would do nothing if there's no interaction with user (silently fail)
- after seeing prompt with text, user doesn't press 'ctrl/cmd+c'

**Comment by lijicheng123** [comment]
> @lijicheng123 I don't think there's much that can be done in that regards.
> many things can go wrong:
> 
> * a generic exception (hopefully we fix this for different platforms, but there are some exotic cases)
> * security measures taken by browser, that will mean copy would do nothing if there's no interaction with user (silently fail)
> * after seeing prompt with text, user doesn't press 'ctrl/cmd+c'

thx very much
